# Generated by Django 4.0.3 on 2022-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
